repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: markdown-toc
        files: ^README.md$

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.15.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [ black==23.7.0 ]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: mypy --show-error-codes
        types: [ python ]
