name: Check code

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: |
          pipx install poetry==1.6.1
          poetry --version
          poetry self show plugins
          poetry config virtualenvs.in-project true

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
          cache: poetry

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Check formatting with Black
        run: poetry run black --check .

      - name: Type check with Mypy
        run: poetry run mypy

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: |
          pipx install poetry==1.6.1
          poetry --version
          poetry self show plugins
          poetry config virtualenvs.in-project true

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python_version }}"
          cache: poetry

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Show Python version
        run: poetry run python --version

      - name: Run tests
        run: poetry run pytest
