name: Deploy Python package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: |
          pipx install poetry==1.6.1
          poetry --version
          poetry self show plugins
          poetry config virtualenvs.in-project true

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
          cache: poetry

      - name: Publish on PyPi
        run: poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
